# SPDX-FileCopyrightText: 2024-2026 Cloudflare Inc., Luke Curley, Mike English and contributors
# SPDX-FileCopyrightText: 2023-2024 Luke Curley and contributors
# SPDX-License-Identifier: MIT OR Apache-2.0

[workspace]
members = [
	"moq-transport",
	"moq-relay-ietf",
	"moq-pub",
	"moq-sub",
	"moq-api",
	"moq-clock-ietf",
	"moq-native-ietf",
	"moq-catalog",
	"moq-test-client",
	"moq-auth",
	"moq-auth-privacypass",
]
resolver = "2"

[workspace.dependencies]
web-transport = { git = "https://github.com/thibmeu/web-transport", rev = "6fd255b6f3d3a5ba8924fb11ea0004473d907c8f" }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[patch.crates-io]
web-transport-quinn = { git = "https://github.com/thibmeu/web-transport", rev = "6fd255b6f3d3a5ba8924fb11ea0004473d907c8f" }

# Use debug symbols in production until things are more stable
[profile.release]
debug = true
