//! Parse relay TOPN_EVENT logs and generate timeline visualization SVG.
//!
//! Usage:
//!   cargo run -p moq-topn-test --bin topn-log-to-svg -- input.log output.svg
//!
//! The input log should contain lines with `TOPN_EVENT:{...}` JSON events
//! generated by running the relay with `--topn-log` or `TOPN_LOG=1`.

use std::collections::HashMap;
use std::fs::File;
use std::io::{BufRead, BufReader, Write};

#[derive(Debug)]
struct LogEvent {
    ts_ms: u64,
    event: String,
    track: Option<String>,
    value: Option<u64>,
    old_value: Option<u64>,
    new_value: Option<u64>,
    publisher_id: Option<u64>,
    subscriber_id: Option<u64>,
    n: Option<u8>,
    selected: Option<Vec<SelectedTrack>>,
    excluded_self: Option<u64>,
}

#[derive(Debug)]
struct SelectedTrack {
    track: String,
    value: u64,
}

fn parse_log_line(line: &str) -> Option<LogEvent> {
    let json_start = line.find("TOPN_EVENT:")?;
    let json_str = &line[json_start + 11..];

    let parsed: serde_json::Value = serde_json::from_str(json_str).ok()?;

    let ts_ms = parsed["ts_ms"].as_u64()?;
    let event = parsed["event"].as_str()?.to_string();

    let track = parsed["track"].as_str().map(|s| s.to_string());
    let value = parsed["value"].as_u64();
    let old_value = parsed["old_value"].as_u64();
    let new_value = parsed["new_value"].as_u64();
    let publisher_id = parsed["publisher_id"].as_u64();
    let subscriber_id = parsed["subscriber_id"].as_u64();
    let n = parsed["n"].as_u64().map(|v| v as u8);
    let excluded_self = parsed["excluded_self"].as_u64();

    let selected = parsed["selected"].as_array().map(|arr| {
        arr.iter()
            .filter_map(|v| {
                Some(SelectedTrack {
                    track: v["track"].as_str()?.to_string(),
                    value: v["value"].as_u64()?,
                })
            })
            .collect()
    });

    Some(LogEvent {
        ts_ms,
        event,
        track,
        value,
        old_value,
        new_value,
        publisher_id,
        subscriber_id,
        n,
        selected,
        excluded_self,
    })
}

struct TimelineBuilder {
    // Track name -> publisher_id mapping
    track_to_publisher: HashMap<String, u64>,
    // Publisher ID -> display index
    publisher_indices: HashMap<u64, usize>,
    // Subscriber ID -> display index
    subscriber_indices: HashMap<u64, usize>,
    // Timeline events for publishers: (ts_ms, publisher_idx, value)
    publisher_events: Vec<(u64, usize, u64)>,
    // Timeline events for subscribers: (ts_ms, subscriber_idx, selected_publisher_indices, excluded_self_idx)
    subscriber_events: Vec<(u64, usize, Vec<usize>, Option<usize>)>,
    // Max timestamp seen
    max_ts: u64,
    // N value (from first query)
    top_n: u8,
}

impl TimelineBuilder {
    fn new() -> Self {
        Self {
            track_to_publisher: HashMap::new(),
            publisher_indices: HashMap::new(),
            subscriber_indices: HashMap::new(),
            publisher_events: Vec::new(),
            subscriber_events: Vec::new(),
            max_ts: 0,
            top_n: 3,
        }
    }

    fn process_event(&mut self, event: LogEvent) {
        self.max_ts = self.max_ts.max(event.ts_ms);

        match event.event.as_str() {
            "track_registered" => {
                if let (Some(track), Some(publisher_id), Some(value)) =
                    (event.track, event.publisher_id, event.value)
                {
                    self.track_to_publisher.insert(track, publisher_id);
                    let pub_idx = self.get_or_create_publisher_idx(publisher_id);
                    self.publisher_events.push((event.ts_ms, pub_idx, value));
                }
            }
            "value_updated" => {
                if let (Some(track), Some(new_value)) = (event.track.clone(), event.new_value) {
                    if let Some(&publisher_id) = self.track_to_publisher.get(&track) {
                        let pub_idx = self.get_or_create_publisher_idx(publisher_id);
                        self.publisher_events.push((event.ts_ms, pub_idx, new_value));
                    }
                }
            }
            "track_removed" => {
                if let Some(track) = event.track {
                    if let Some(&publisher_id) = self.track_to_publisher.get(&track) {
                        let pub_idx = self.get_or_create_publisher_idx(publisher_id);
                        self.publisher_events.push((event.ts_ms, pub_idx, 0));
                    }
                }
            }
            "top_n_query" => {
                if let (Some(subscriber_id), Some(n), Some(selected)) =
                    (event.subscriber_id, event.n, event.selected)
                {
                    self.top_n = n;
                    let sub_idx = self.get_or_create_subscriber_idx(subscriber_id);

                    // Map selected tracks to publisher indices
                    // First collect publisher IDs, then map to indices
                    let publisher_ids: Vec<u64> = selected
                        .iter()
                        .filter_map(|s| self.track_to_publisher.get(&s.track).copied())
                        .collect();
                    let selected_pub_indices: Vec<usize> = publisher_ids
                        .iter()
                        .map(|&pid| self.get_or_create_publisher_idx(pid))
                        .collect();

                    // Map excluded_self to publisher index
                    let excluded_idx = event
                        .excluded_self
                        .map(|pid| self.get_or_create_publisher_idx(pid));

                    self.subscriber_events
                        .push((event.ts_ms, sub_idx, selected_pub_indices, excluded_idx));
                }
            }
            _ => {}
        }
    }

    fn get_or_create_publisher_idx(&mut self, publisher_id: u64) -> usize {
        let next_idx = self.publisher_indices.len();
        *self.publisher_indices.entry(publisher_id).or_insert(next_idx)
    }

    fn get_or_create_subscriber_idx(&mut self, subscriber_id: u64) -> usize {
        let next_idx = self.subscriber_indices.len();
        *self.subscriber_indices.entry(subscriber_id).or_insert(next_idx)
    }

    fn generate_svg(&self, output_path: &str) -> std::io::Result<()> {
        let num_publishers = self.publisher_indices.len().max(1);
        let num_subscribers = self.subscriber_indices.len().max(1);
        let max_time_ms = self.max_ts.max(1000);

        let margin_left = 120.0;
        let margin_right = 40.0;
        let margin_top = 60.0;
        let margin_bottom = 40.0;

        let publisher_lane_height = 40.0;
        let subscriber_lane_height = 50.0;
        let section_gap = 30.0;
        let legend_height = 80.0;

        let timeline_width = 1000.0;
        let publishers_height = num_publishers as f64 * publisher_lane_height;
        let subscribers_height = num_subscribers as f64 * subscriber_lane_height;

        let total_width = margin_left + timeline_width + margin_right;
        let total_height = margin_top
            + publishers_height
            + section_gap
            + subscribers_height
            + section_gap
            + legend_height
            + margin_bottom;

        let mut svg = String::new();
        svg.push_str(&format!(
            r#"<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {} {}" width="{}" height="{}">"#,
            total_width, total_height, total_width, total_height
        ));
        svg.push('\n');

        // Styles
        svg.push_str(
            r#"<defs>
  <style>
    .title { font: bold 18px sans-serif; fill: #333; }
    .section-label { font: bold 14px sans-serif; fill: #555; }
    .lane-label { font: 12px sans-serif; fill: #666; }
    .time-label { font: 10px sans-serif; fill: #888; }
    .legend-text { font: 11px sans-serif; fill: #555; }
    .speech-silent { fill: #e0e0e0; }
    .speech-active { fill: #4CAF50; }
    .speech-start { fill: #FF9800; }
    .selected { fill: #2196F3; opacity: 0.7; }
    .excluded { fill: #f44336; opacity: 0.5; }
    .grid-line { stroke: #eee; stroke-width: 1; }
    .axis-line { stroke: #ccc; stroke-width: 1; }
  </style>
</defs>
"#,
        );

        // Title
        svg.push_str(&format!(
            r#"<text x="{}" y="30" class="title">Top-N Filtering Timeline (from relay logs, {} publishers, {} subscribers, N={})</text>"#,
            total_width / 2.0 - 200.0,
            num_publishers,
            num_subscribers,
            self.top_n
        ));
        svg.push('\n');

        // Build publisher timelines
        let mut publisher_timelines: HashMap<usize, Vec<(u64, u64)>> = HashMap::new();
        for i in 0..num_publishers {
            publisher_timelines.insert(i, vec![(0, 0)]);
        }
        for (ts, pub_idx, value) in &self.publisher_events {
            if let Some(timeline) = publisher_timelines.get_mut(pub_idx) {
                timeline.push((*ts, *value));
            }
        }
        for (_, timeline) in publisher_timelines.iter_mut() {
            let last_val = timeline.last().map(|(_, v)| *v).unwrap_or(0);
            timeline.push((max_time_ms, last_val));
        }

        // Publishers section label
        svg.push_str(&format!(
            r#"<text x="10" y="{}" class="section-label">Publishers</text>"#,
            margin_top - 10.0
        ));
        svg.push('\n');

        // Draw publisher lanes
        for pub_idx in 0..num_publishers {
            let lane_y = margin_top + pub_idx as f64 * publisher_lane_height;

            // Lane label
            svg.push_str(&format!(
                r#"<text x="{}" y="{}" class="lane-label">P{}</text>"#,
                margin_left - 40.0,
                lane_y + publisher_lane_height / 2.0 + 4.0,
                pub_idx
            ));
            svg.push('\n');

            // Draw speech activity bars
            if let Some(timeline) = publisher_timelines.get(&pub_idx) {
                for i in 0..timeline.len() - 1 {
                    let (t1, v1) = timeline[i];
                    let (t2, _) = timeline[i + 1];

                    let x1 = margin_left + (t1 as f64 / max_time_ms as f64) * timeline_width;
                    let x2 = margin_left + (t2 as f64 / max_time_ms as f64) * timeline_width;
                    let width = (x2 - x1).max(1.0);

                    let class = match v1 {
                        0 => "speech-silent",
                        1 => "speech-active",
                        2 => "speech-start",
                        _ => "speech-active",
                    };

                    svg.push_str(&format!(
                        r#"<rect x="{}" y="{}" width="{}" height="{}" class="{}" />"#,
                        x1,
                        lane_y + 5.0,
                        width,
                        publisher_lane_height - 10.0,
                        class
                    ));
                    svg.push('\n');
                }
            }

            // Lane border
            svg.push_str(&format!(
                r#"<line x1="{}" y1="{}" x2="{}" y2="{}" class="axis-line" />"#,
                margin_left,
                lane_y + publisher_lane_height,
                margin_left + timeline_width,
                lane_y + publisher_lane_height
            ));
            svg.push('\n');
        }

        // Subscribers section
        let subscribers_y = margin_top + publishers_height + section_gap;
        svg.push_str(&format!(
            r#"<text x="10" y="{}" class="section-label">Subscribers (Top-N Selection)</text>"#,
            subscribers_y - 10.0
        ));
        svg.push('\n');

        // Build subscriber timelines
        let mut subscriber_timelines: HashMap<usize, Vec<(u64, Vec<usize>, Option<usize>)>> =
            HashMap::new();
        for i in 0..num_subscribers {
            subscriber_timelines.insert(i, vec![(0, vec![], None)]);
        }
        for (ts, sub_idx, selected, excluded) in &self.subscriber_events {
            if let Some(timeline) = subscriber_timelines.get_mut(sub_idx) {
                timeline.push((*ts, selected.clone(), *excluded));
            }
        }
        for (_, timeline) in subscriber_timelines.iter_mut() {
            let last = timeline.last().cloned().unwrap_or((0, vec![], None));
            timeline.push((max_time_ms, last.1, last.2));
        }

        // Draw subscriber lanes
        for sub_idx in 0..num_subscribers {
            let lane_y = subscribers_y + sub_idx as f64 * subscriber_lane_height;

            // Lane label
            svg.push_str(&format!(
                r#"<text x="{}" y="{}" class="lane-label">S{}</text>"#,
                margin_left - 40.0,
                lane_y + subscriber_lane_height / 2.0 + 4.0,
                sub_idx
            ));
            svg.push('\n');

            // Draw selection segments
            if let Some(timeline) = subscriber_timelines.get(&sub_idx) {
                for i in 0..timeline.len() - 1 {
                    let (t1, ref selected, excluded) = timeline[i];
                    let (t2, _, _) = timeline[i + 1];

                    let x1 = margin_left + (t1 as f64 / max_time_ms as f64) * timeline_width;
                    let x2 = margin_left + (t2 as f64 / max_time_ms as f64) * timeline_width;
                    let width = (x2 - x1).max(1.0);

                    // Background
                    svg.push_str(&format!(
                        r##"<rect x="{}" y="{}" width="{}" height="{}" fill="#f5f5f5" />"##,
                        x1,
                        lane_y + 2.0,
                        width,
                        subscriber_lane_height - 4.0
                    ));
                    svg.push('\n');

                    // Draw mini bars for each selected publisher
                    let bar_height = (subscriber_lane_height - 8.0) / num_publishers as f64;
                    let bar_width = (width - 2.0).max(1.0);
                    for &pub_idx in selected {
                        if pub_idx < num_publishers {
                            let bar_y = lane_y + 4.0 + pub_idx as f64 * bar_height;
                            svg.push_str(&format!(
                                r#"<rect x="{}" y="{}" width="{}" height="{}" class="selected" />"#,
                                x1 + 1.0,
                                bar_y,
                                bar_width,
                                bar_height - 1.0
                            ));
                            svg.push('\n');
                        }
                    }

                    // Mark excluded self
                    if let Some(excl_idx) = excluded {
                        if excl_idx < num_publishers {
                            let bar_y = lane_y + 4.0 + excl_idx as f64 * bar_height;
                            svg.push_str(&format!(
                                r#"<rect x="{}" y="{}" width="{}" height="{}" class="excluded" />"#,
                                x1 + 1.0,
                                bar_y,
                                bar_width,
                                bar_height - 1.0
                            ));
                            svg.push('\n');
                        }
                    }
                }
            }

            // Lane border
            svg.push_str(&format!(
                r#"<line x1="{}" y1="{}" x2="{}" y2="{}" class="axis-line" />"#,
                margin_left,
                lane_y + subscriber_lane_height,
                margin_left + timeline_width,
                lane_y + subscriber_lane_height
            ));
            svg.push('\n');
        }

        // Time axis with labels
        let axis_y = subscribers_y + subscribers_height + 20.0;
        svg.push_str(&format!(
            r#"<line x1="{}" y1="{}" x2="{}" y2="{}" class="axis-line" />"#,
            margin_left,
            axis_y,
            margin_left + timeline_width,
            axis_y
        ));
        svg.push('\n');

        // Time ticks (every 5 seconds)
        let tick_interval_ms = 5000u64;
        let mut t = 0u64;
        while t <= max_time_ms {
            let x = margin_left + (t as f64 / max_time_ms as f64) * timeline_width;
            svg.push_str(&format!(
                r#"<line x1="{}" y1="{}" x2="{}" y2="{}" class="axis-line" />"#,
                x,
                axis_y,
                x,
                axis_y + 5.0
            ));
            svg.push_str(&format!(
                r#"<text x="{}" y="{}" class="time-label" text-anchor="middle">{}s</text>"#,
                x,
                axis_y + 18.0,
                t / 1000
            ));
            svg.push('\n');
            t += tick_interval_ms;
        }

        // Legend
        let legend_y = axis_y + 35.0;
        svg.push_str(&format!(
            r#"<text x="{}" y="{}" class="section-label">Legend</text>"#,
            margin_left, legend_y
        ));
        svg.push('\n');

        let legend_items = [
            ("speech-silent", "Silent (0)"),
            ("speech-active", "Speaking (1)"),
            ("speech-start", "Speech Start (2)"),
            ("selected", "Selected in Top-N"),
            ("excluded", "Self-Excluded"),
        ];

        let mut lx = margin_left;
        for (class, label) in legend_items {
            svg.push_str(&format!(
                r#"<rect x="{}" y="{}" width="20" height="12" class="{}" />"#,
                lx,
                legend_y + 10.0,
                class
            ));
            svg.push_str(&format!(
                r#"<text x="{}" y="{}" class="legend-text">{}</text>"#,
                lx + 25.0,
                legend_y + 20.0,
                label
            ));
            svg.push('\n');
            lx += 150.0;
        }

        svg.push_str("</svg>\n");

        let mut file = File::create(output_path)?;
        file.write_all(svg.as_bytes())?;

        Ok(())
    }
}

fn main() -> anyhow::Result<()> {
    let args: Vec<String> = std::env::args().collect();

    if args.len() < 3 {
        eprintln!("Usage: {} <input.log> <output.svg>", args[0]);
        eprintln!();
        eprintln!("Parses TOPN_EVENT logs from the relay and generates a timeline SVG.");
        eprintln!();
        eprintln!("To generate logs, run the relay with --topn-log or TOPN_LOG=1:");
        eprintln!("  TOPN_LOG=1 cargo run -p moq-relay-ietf ... 2>&1 | tee relay.log");
        eprintln!();
        eprintln!("Then extract and visualize:");
        eprintln!("  grep TOPN_EVENT relay.log > topn.log");
        eprintln!("  {} topn.log timeline.svg", args[0]);
        std::process::exit(1);
    }

    let input_path = &args[1];
    let output_path = &args[2];

    println!("Reading log file: {}", input_path);

    let file = File::open(input_path)?;
    let reader = BufReader::new(file);

    let mut builder = TimelineBuilder::new();
    let mut event_count = 0;

    for line in reader.lines() {
        let line = line?;
        if let Some(event) = parse_log_line(&line) {
            builder.process_event(event);
            event_count += 1;
        }
    }

    println!("Processed {} events", event_count);
    println!(
        "Found {} publishers, {} subscribers",
        builder.publisher_indices.len(),
        builder.subscriber_indices.len()
    );
    println!("Timeline duration: {}ms", builder.max_ts);

    println!("Generating SVG: {}", output_path);
    builder.generate_svg(output_path)?;

    println!("Done!");
    Ok(())
}
